"""Integration tests for the REST API (SQLite backend, no network access)."""


def _create_project(client, name="apitest"):
    resp = client.post("/projects", json={"name": name, "description": "d"})
    assert resp.status_code == 201
    return resp.json()


def test_project_crud(client):
    created = _create_project(client)
    pid = created["id"]
    assert client.get("/projects").status_code == 200
    got = client.get(f"/projects/{pid}")
    assert got.status_code == 200 and got.json()["name"] == "apitest"

    dup = client.post("/projects", json={"name": "apitest"})
    assert dup.status_code == 409

    patched = client.patch(f"/projects/{pid}", json={"description": "new"})
    assert patched.json()["description"] == "new"

    assert client.delete(f"/projects/{pid}").status_code == 204
    assert client.get(f"/projects/{pid}").status_code == 404


def test_target_add_seeds_allow_scope(client):
    pid = _create_project(client)["id"]
    resp = client.post(f"/projects/{pid}/targets",
                       json=[{"value": "Example.COM", "target_type": "domain"}])
    assert resp.status_code == 201
    assert resp.json()[0]["value"] == "example.com"

    rules = client.get(f"/projects/{pid}/scope").json()
    assert any(r["pattern"] == "example.com" and r["rule_type"] == "ALLOW" for r in rules)

    bad = client.post(f"/projects/{pid}/targets",
                      json=[{"value": "not a domain", "target_type": "domain"}])
    assert bad.status_code == 422


def test_scope_rules_crud_and_deny(client):
    pid = _create_project(client)["id"]
    resp = client.post(f"/projects/{pid}/scope", json=[
        {"pattern": "*.example.com", "rule_type": "ALLOW"},
        {"pattern": "admin.example.com", "rule_type": "DENY"},
    ])
    assert resp.status_code == 201
    rules = client.get(f"/projects/{pid}/scope").json()
    assert len(rules) == 2
    rule_id = rules[0]["id"]
    assert client.delete(f"/projects/{pid}/scope/{rule_id}").status_code == 204


def test_scan_lifecycle_queue_and_stop(client, project_id):
    created = client.post(f"/projects/{project_id}/scans",
                          json={"profile": "standard"})
    assert created.status_code == 202
    scan = created.json()
    assert scan["status"] == "queued"

    conflict = client.post(f"/projects/{project_id}/scans",
                           json={"profile": "quick"})
    assert conflict.status_code == 409

    stopped = client.post(f"/scans/{scan['id']}/stop")
    assert stopped.status_code == 200
    assert stopped.json()["status"] == "stopped"

    tasks = client.get(f"/scans/{scan['id']}/tasks")
    assert tasks.status_code == 200


def test_assets_findings_graph_stats_endpoints(client, project_id, session_factory):
    from backend.models.entities import AssetType
    from tests.conftest import make_asset, make_dns_record

    sub = make_asset(session_factory, project_id, "api.example.com",
                     asset_type=AssetType.SUBDOMAIN,
                     priority_score=55,
                     priority_reasons=[{"reason": "live_http_service", "points": 10}])
    make_asset(session_factory, project_id, "1.2.3.4", asset_type=AssetType.IP)
    make_dns_record(session_factory, sub, "A", "1.2.3.4")

    # relationships are generated by the correlation engine (as in a real scan)
    from engine.correlation import build_relationships

    with session_factory() as s:
        build_relationships(s, project_id, None)
        s.commit()

    assets = client.get(f"/projects/{project_id}/assets").json()
    assert {a["value"] for a in assets} == {"api.example.com", "1.2.3.4"}

    filtered = client.get(
        f"/projects/{project_id}/assets",
        params={"asset_type": "subdomain", "min_score": 50}).json()
    assert [a["id"] for a in filtered] == [str(sub)]

    detail = client.get(f"/projects/{project_id}/assets/{sub}")
    assert detail.status_code == 200
    body = detail.json()
    assert any(r["record_type"] == "A" and r["value"] == "1.2.3.4"
               for r in body["dns_records"])

    graph = client.get(f"/projects/{project_id}/graph").json()
    node_labels = {n["label"] for n in graph["nodes"]}
    edge_types = {e["rel_type"] for e in graph["edges"]}
    assert {"api.example.com", "1.2.3.4"} <= node_labels
    assert "RESOLVES_TO" in edge_types

    stats = client.get(f"/projects/{project_id}/statistics").json()
    assert stats["assets"] == 2
    assert stats["ips"] == 1
    assert stats["high_priority_assets"] >= 1

    findings = client.get(f"/projects/{project_id}/findings")
    assert findings.status_code == 200


def test_report_exports(client, project_id, session_factory):
    from tests.conftest import make_asset

    make_asset(session_factory, project_id, "api.example.com", priority_score=42)
    for fmt, marker in [("json", b'"api.example.com"'), ("csv", b"api.example.com"),
                        ("markdown", b"# ReconPulse Report"),
                        ("html", b"<html>")]:
        resp = client.get(f"/projects/{project_id}/report", params={"format": fmt})
        assert resp.status_code == 200
        assert marker in resp.content

    bad = client.get(f"/projects/{project_id}/report", params={"format": "xml"})
    assert bad.status_code == 422


def test_health(client):
    assert client.get("/health").json() == {"status": "ok"}
